import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/request";

export default function Home(props) {
  console.log(props.results);
  return (
    <div className="">
      <Head>
        <title>movie app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hulu.ico" />
      </Head>
      <Header />
      <Nav />
      {/* <Image
        className="object-contain"
        src="https://www.hulu.com/static/hitch/s3/attachments/ckdz36xqi7zz019ym0b2seyqk-dplus-logo-0-1-2-0.full.png"
        width="500"
        height="200"
      /> */}
      <Results result={props.results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
